FUNCTION FGetSystemName : STRING(31) #DUMMY_EDIT_BLOCK

VAR CONSTANT
 sSYSTEMNAME : STRING(31) := 'KePlast i2980';
END_VAR
#BEGIN_EDIT_BLOCK
FGetSystemName := sSYSTEMNAME;


;#END_EDIT_BLOCK END_FUNCTION



#END_OF_IEC_PART

@Puma @IecEditor 6 80 @Pou 25 
@@@BEG_Comment@@@

@@@END_Comment@@@

@BEG_Contents 

@BEG_Func 
@RT(17)FuncTreeContainer 
0 
@END_Func 

@BEG_Const 
@RT(18)ConstTreeContainer 
0 
@END_Const 

@BEG_Export 

@BEG_Kind 
@FUNCTION @RT(14)FGetSystemName @STRUCTURED_TEXT 
@RT(10)STRING(31) @RT(0) @RT(0) 
@END_Kind 

@BEG_Dcl 
@RT(16)DclTreeContainer 
1 
@Var @RT(11)sSYSTEMNAME @RT(0) @T @F @DT @RT(10)STRING(31) @RT(0) @T @T @STRING 0 @F @RT(2)31 @F 
@F @F 
@T 
@BEG_Attrib 
3 @RT(15)'KePlast i2980' @RT(0) @RT(0) 
@END_Attrib 
1 15 @F @F @F @F 

@END_Dcl 

@END_Export 

@BEG_Body 
@TL(2)
FGetSystemName := sSYSTEMNAME;

@END_Body 

@END_Contents 
