(*
calculate screw plane in mm^2

*)

FUNCTION FCalcScrewSize : REAL #DUMMY_EDIT_BLOCK

VAR_INPUT
 rDiameter : REAL (* diameter of screw in mm *);
END_VAR

VAR CONSTANT
 PI : REAL := 3.14159265;
END_VAR
#BEGIN_EDIT_BLOCK
(**************************************** WARNING ********************************************
 *** The KEBA Kemro K2 System including software is not intended for safety control tasks! ***
 ***                       For further information see Comment tab!                        ***
 *********************************************************************************************)

(* calculate screw plane in mm^2 *)
FCalcScrewSize := EXPT(rDiameter, 2.0) * PI / 4.0


;#END_EDIT_BLOCK END_FUNCTION



#END_OF_IEC_PART

@Puma @IecEditor 6 30 @Pou 25 
@@@BEG_Comment@@@
calculate screw plane in mm^2

@@@END_Comment@@@

@BEG_Contents 

@BEG_Func 
@RT(17)FuncTreeContainer 
0 
@END_Func 

@BEG_Const 
@RT(18)ConstTreeContainer 
0 
@END_Const 

@BEG_Export 

@BEG_Kind 
@FUNCTION @RT(14)FCalcScrewSize @STRUCTURED_TEXT 
@RT(4)REAL @RT(0) @RT(0) 
@END_Kind 

@BEG_Dcl 
@RT(16)DclTreeContainer 
2 
@Var @RT(9)rDiameter @RT(0) @T @F @DT @RT(4)REAL @RT(0) @T @T @BASIC 0 @F 
@F @F 
@T 
@BEG_Attrib 
3 @RT(0) @RT(23)diameter of screw in mm @RT(0) 
@END_Attrib 
1 1 @F @F @F @F 

@Var @RT(2)PI @RT(0) @T @F @DT @RT(4)REAL @RT(0) @T @T @BASIC 0 @F 
@F @F 
@T 
@BEG_Attrib 
3 @RT(10)3.14159265 @RT(0) @RT(0) 
@END_Attrib 
1 15 @F @F @F @F 

@END_Dcl 

@END_Export 

@BEG_Body 
@TL(8)
(**************************************** WARNING ********************************************
 *** The KEBA Kemro K2 System including software is not intended for safety control tasks! ***
 ***                       For further information see Comment tab!                        ***
 *********************************************************************************************)

(* calculate screw plane in mm^2 *)
FCalcScrewSize := EXPT(rDiameter, 2.0) * PI / 4.0

@END_Body 

@END_Contents 
