IMPORT_OVER_LISTFILE
 KCAT_HandleData
, KCAT_Status

END_IMPORT

FUNCTION_BLOCK FBEPUnForceAI #DUMMY_EDIT_BLOCK

VAR_INPUT
 sSysVar : STRING(255);
END_VAR

VAR
 StatusName : KCAT_HandleData;
 Status : KCAT_Status;
END_VAR
#BEGIN_EDIT_BLOCK
StatusName := KCAT_GetHandleFromEPName(sSysVar);                             
Status := KCAT_UnForce(Handle := StatusName.Handle);



;#END_EDIT_BLOCK END_FUNCTION_BLOCK



#END_OF_IEC_PART

@Puma @IecEditor 6 22 @Pou 25 
@@@BEG_Comment@@@

@@@END_Comment@@@

@BEG_Contents 

@BEG_Func 
@RT(17)FuncTreeContainer 
0 
@END_Func 

@BEG_Const 
@RT(18)ConstTreeContainer 
0 
@END_Const 

@BEG_Export 

@BEG_Kind 
@FUNCTION_BLOCK @RT(13)FBEPUnForceAI @STRUCTURED_TEXT 
@RT(0) @RT(0) @RT(0) 
@END_Kind 

@BEG_Dcl 
@RT(16)DclTreeContainer 
3 
@Var @RT(7)sSysVar @RT(0) @T @F @DT @RT(11)STRING(255) @RT(0) @T @T @STRING 0 @F @RT(3)255 @F 
@F @F 
@T 
@BEG_Attrib 
3 @RT(0) @RT(0) @RT(0) 
@END_Attrib 
1 1 @F @F @F @F 

@Var @RT(10)StatusName @RT(0) @T @T @DERIVED 0 @T @T @DT @RT(15)KCAT_HandleData @RT(0) @T @T @UNKNOWN 0 @F 
@F @F 
@T 
@BEG_Attrib 
3 @RT(0) @RT(0) @RT(0) 
@END_Attrib 
1 0 @F @F @F @F 

@Var @RT(6)Status @RT(0) @T @T @DERIVED 0 @T @T @DT @RT(11)KCAT_Status @RT(0) @T @T @UNKNOWN 0 @F 
@F @F 
@T 
@BEG_Attrib 
3 @RT(0) @RT(0) @RT(0) 
@END_Attrib 
1 0 @F @F @F @F 

@END_Dcl 

@END_Export 

@BEG_Body 
@TL(4)
StatusName := KCAT_GetHandleFromEPName(sSysVar);                             
Status := KCAT_UnForce(Handle := StatusName.Handle);


@END_Body 

@END_Contents 
